### ISSUE TITLE
Network issue on LG G6

### ISSUE THREAD

**Issue by kater162** [pangz-lab/verus_box-release#2] opened 2022-04-16 02:23 UTC
Home screen only displays below error. 

"An error has occurred.
Please check your network and try again"

Tried multiple wifi connections and restarting the app many times.
Both PlayStore and direct from github have this issue.
Only present on this one device, other devices on the same wifi don't show this error.

Device information:
Model LG-H870
Build: NRD90U
Android Version: 7.0
Architecture: arm64-v8a

**Comment by pangz-lab** [comment] 2022-04-17 03:34
Hello @kater162, 

Thank you for reporting this. I'll look into it.


For now, the only reason I could think of is probably due to lack of ssl certificate on your phone. These certificates are pre-loaded and sent whenever a network request is done to a server. Some servers require specific set of certificates. If absent, this issue happens.

If this is the case, this is somehow a bit of a challenge. I haven't found any reliable solutions yet. 

I'll let you know when this issue is fixed.

Cheers
Pangz

**Comment by kater162** [comment] 2022-04-18 10:42
Hi Pangz,

Let me know if there is something that I can check and provide on my end that could help.

Your app has been the easiest to deal with when it comes to phone mining to keen to get this fixed.

Regards.

**Comment by pangz-lab** [comment] 2022-04-19 14:43
> Hi Pangz,
> 
> Let me know if there is something that I can check and provide on my end that could help.
> 
> Your app has been the easiest to deal with when it comes to phone mining to keen to get this fixed.
> 
> Regards.

Hello Kater,

I have fixed this issue in version 0.1.22. It will be available in playstore soon. I'll be releasing the latest build as well in this repo.

Cheers

**Comment by pangz-lab** [comment] 2022-04-19 15:41
Hello @kater162 ,

Please see the latest release. https://github.com/pangz-lab/verus_box-release/releases/tag/v0.1.22
I'll close this issue once you've confirmed the behavior.

Thanks

**Comment by kater162** [comment] 2022-04-20 06:30
Hi Pangz,

Thanks for the update.
That has solved the issue and app is working as normal.

Regards.

**Comment by pangz-lab** [comment] 2022-04-20 12:12
> Hi Pangz,
> 
> Thanks for the update.
> That has solved the issue and app is working as normal.
> 
> Regards.

Great. Thank you @kater162 . I'll close this issue now.

**Closed** 2022-04-20 12:12 UTC
